name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Run Tests on PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Laravel 12 requires PHP 8.2+
          - php-version: 8.4
            laravel: 12.*
          - php-version: 8.3
            laravel: 12.*
          - php-version: 8.2
            laravel: 12.*

          # Laravel 11 requires PHP 8.1+
          - php-version: 8.4
            laravel: 11.*
          - php-version: 8.3
            laravel: 11.*
          - php-version: 8.2
            laravel: 11.*
          - php-version: 8.1
            laravel: 11.*

          # Laravel 10 requires PHP 8.0+
          - php-version: 8.4
            laravel: 10.*
          - php-version: 8.3
            laravel: 10.*
          - php-version: 8.2
            laravel: 10.*
          - php-version: 8.1
            laravel: 10.*
          - php-version: 8.0
            laravel: 10.*

          # Laravel 9 requires PHP 8.0 - 8.1
          - php-version: 8.1
            laravel: 9.*
          - php-version: 8.0
            laravel: 9.*

          # Laravel 8 requires PHP 7.3 - 8.1 (but 7.x is EOL)
          - php-version: 8.1
            laravel: 8.*
          - php-version: 8.0
            laravel: 8.*

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-suggest
      - name: Run Tests
        run: composer test
