name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests on PHP ${{ matrix.php-version }} with Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Laravel 12 requires PHP 8.2+
          - php-version: 8.4
            laravel: 12.*
            pest: ^3.0
          - php-version: 8.3
            laravel: 12.*
            pest: ^3.0
          - php-version: 8.2
            laravel: 12.*
            pest: ^3.0

          # Laravel 11 requires PHP 8.1+
          - php-version: 8.4
            laravel: 11.*
            pest: ^3.0
          - php-version: 8.3
            laravel: 11.*
            pest: ^3.0
          - php-version: 8.2
            laravel: 11.*
            pest: ^3.0
          - php-version: 8.1
            laravel: 11.*
            pest: ^3.0

          # Laravel 10 requires PHP 8.0+
          - php-version: 8.4
            laravel: 10.*
            pest: ^2.0
          - php-version: 8.3
            laravel: 10.*
            pest: ^2.0
          - php-version: 8.2
            laravel: 10.*
            pest: ^2.0
          - php-version: 8.1
            laravel: 10.*
            pest: ^2.0

          # Laravel 9 requires PHP 8.0 - 8.1
          - php-version: 8.1
            laravel: 9.*
            pest: ^1.0
          - php-version: 8.0
            laravel: 9.*
            pest: ^1.0
            
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer

      - name: Remove Existing Composer Lock
        run: rm -f composer.lock

      - name: Configure Laravel Version
        run: composer require laravel/framework:${{ matrix.laravel }} --no-update

      - name: Configure Pest Version
        run: composer require pestphp/pest:${{ matrix.pest }} --dev --no-update

      - name: Install Dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Run Tests
        run: composer test